name: Review Pipeline

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  # run-sfdx-scanner:
  #   uses: ./.github/workflows/run-sfdx-scanner.yml
  #   secrets: inherit

  pr-review:
    # needs: run-sfdx-scanner
    uses: ./.github/workflows/pr-review.yml
    secrets: inherit
